name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}


jobs:
  build-packages:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:

      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          miniconda-version: "latest"
          activate-environment: gmsh
          channels: conda-forge

      - name: build
        run: |
          conda install compas -y
          pip install -r requirements-dev.txt
  
      - name: Lint with flake8
        run: |
          invoke lint

      - name: Test with pytest
        run: |
          invoke test
